server.port=8081

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/gestionOrdenesDb
spring.datasource.username=alejandro
spring.datasource.password=alejandro123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.jackson.property-naming-strategy=SNAKE_CASE
